### ISSUE TITLE
 [!] Unable to determine Swift version for the following pods..

### ISSUE THREAD

**Issue by Goolpe** [Unact/yandex_mapkit#3]
if I try to start debugging on iOS - I get this issue. 
```
Resolving dependencies of `Podfile`
    Comparing resolved specification to the sandbox manifest
    -> Installing yandex_mapkit (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:
    - `yandex_mapkit` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:115:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:459:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:138:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
```

Doctor summary:
```
[✓] Flutter (Channel dev, v1.2.1, on Mac OS X 10.14.3 18D109, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.31.1)
[✓] Connected device (2 available)
```

I added `use_frameworks!` and `config.build_settings['SWIFT_VERSION'] = '4.2'` but nothing changed

**Comment by DCrow** [comment]
Hello!

Have you tried doing [this](https://github.com/flutter/flutter/issues/16049#issuecomment-457890567)?

**Comment by Goolpe** [comment]
Yes, I tried also create new project, downgrade/upgrade pod, add empty swift file, change swift version, but nothing happened...

**Comment by DCrow** [comment]
1. Could you post your Podfile definition? 
2. Does the example from this repo work on your device?

**Comment by Goolpe** [comment]
1. Podfile ```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end

```
2. Example from this repo show me this error:
```
 === BUILD TARGET yandex_mapkit OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:174:10: warning: parameter of 'onObjectAdded(with:)' has different optionality than expected by protocol 'YMKUserLocationObjectListener'
        func onObjectAdded(with view: YMKUserLocationView?) {
             ^                                           ~
    YandexMapKit.YMKUserLocationObjectListener:2:17: note: requirement 'onObjectAdded(with:)' declared here
        public func onObjectAdded(with view: YMKUserLocationView)
                    ^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:180:10: warning: parameter of 'onObjectRemoved(with:)' has different optionality than expected by protocol 'YMKUserLocationObjectListener'
        func onObjectRemoved(with view: YMKUserLocationView?) {}
             ^                                             ~
    YandexMapKit.YMKUserLocationObjectListener:5:17: note: requirement 'onObjectRemoved(with:)' declared here
        public func onObjectRemoved(with view: YMKUserLocationView)
                    ^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:182:10: warning: parameters of 'onObjectUpdated(with:event:)' have different optionality than expected by protocol 'YMKUserLocationObjectListener'
        func onObjectUpdated(with view: YMKUserLocationView?, event: YMKObjectEvent?) {}
             ^                                             ~                       ~
    YandexMapKit.YMKUserLocationObjectListener:8:17: note: requirement 'onObjectUpdated(with:event:)' declared here
        public func onObjectUpdated(with view: YMKUserLocationView, event: YMKObjectEvent)
                    ^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:199:12: warning: parameter of 'onMapObjectTap(with:point:)' has different optionality than expected by protocol 'YMKMapObjectTapListener'
          func onMapObjectTap(with mapObject: YMKMapObject?, point: YMKPoint) -> Bool {
               ^                                          ~
    YandexMapKit.YMKMapObjectTapListener:2:17: note: requirement 'onMapObjectTap(with:point:)' declared here
        public func onMapObjectTap(with mapObject: YMKMapObject, point: YMKPoint) -> Bool
                    ^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:210:10: warning: parameter of 'onMapObjectAdded(with:)' has different optionality than expected by protocol 'YMKMapObjectCollectionListener'
        func onMapObjectAdded(with mapObject: YMKMapObject?) {
             ^                                            ~
    YandexMapKit.YMKMapObjectCollectionListener:2:17: note: requirement 'onMapObjectAdded(with:)' declared here
        public func onMapObjectAdded(with mapObject: YMKMapObject)
                    ^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:214:10: warning: parameter of 'onMapObjectRemoved(with:)' has different optionality than expected by protocol 'YMKMapObjectCollectionListener'
        func onMapObjectRemoved(with mapObject: YMKMapObject?) {
             ^                                              ~
    YandexMapKit.YMKMapObjectCollectionListener:5:17: note: requirement 'onMapObjectRemoved(with:)' declared here
public func onMapObjectRemoved(with mapObject: YMKMapObject)
                    ^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:218:10: warning: parameter of 'onMapObjectUpdated(with:)' has different optionality than expected by protocol 'YMKMapObjectCollectionListener'
        func onMapObjectUpdated(with mapObject: YMKMapObject?) {}
             ^                                              ~
    YandexMapKit.YMKMapObjectCollectionListener:8:17: note: requirement 'onMapObjectUpdated(with:)' declared here
        public func onMapObjectUpdated(with mapObject: YMKMapObject)
                    ^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:23:26: error: cannot force unwrap value of non-optional type '((YMKMapWindow) throws -> _) throws -> _?'
        mapView.mapWindow.map!.mapObjects!.addListener(with: mapObjectCollectionListener)
        ~~~~~~~~~~~~~~~~~~~~~^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:64:50: error: cannot force unwrap value of non-optional type '((YMKMapWindow) throws -> _) throws -> _?'
        let userLocationLayer = mapView.mapWindow.map!.userLocationLayer
                                ~~~~~~~~~~~~~~~~~~~~~^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:73:50: error: cannot force unwrap value of non-optional type '((YMKMapWindow) throws -> _) throws -> _?'
        let userLocationLayer = mapView.mapWindow.map!.userLocationLayer
                                ~~~~~~~~~~~~~~~~~~~~~^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:92:47: error: cannot force unwrap value of non-optional type '((YMKMapWindow) throws -> _) throws -> _?'
        let cameraPosition = mapView.mapWindow.map!.cameraPosition(with:
                             ~~~~~~~~~~~~~~~~~~~~~^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:115:43: error: cannot force unwrap value of non-optional type '((YMKMapWindow) throws -> _) throws -> _?'
        let mapObjects = mapView.mapWindow.map!.mapObjects!
                         ~~~~~~~~~~~~~~~~~~~~~^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:126:43: error: cannot force unwrap value of non-optional type '((YMKMapWindow) throws -> _) throws -> _?'
        let mapObjects = mapView.mapWindow.map!.mapObjects!
                         ~~~~~~~~~~~~~~~~~~~~~^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:146:28: error: cannot force unwrap value of non-optional type '((YMKMapWindow) throws -> _) throws -> _?'
          mapView.mapWindow.map!.move(with: cameraPosition, animationType: animationType)
          ~~~~~~~~~~~~~~~~~~~~~^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:148:28: error: cannot force unwrap value of non-optional type '((YMKMapWindow) throws -> _) throws -> _?'
          mapView.mapWindow.map!.move(with: cameraPosition)
          ~~~~~~~~~~~~~~~~~~~~~^
    /Users/Library/flutter/.pub-cache/git/yandex_mapkit-5c194d63405d90fed52267ed8cfe9b2b9d2c6f79/ios/Classes/YandexMapController.swift:175:16: error: cannot force unwrap value of non-optional type 'YMKPlacemarkMapObject'
          view!.pin!.setIconWith(
          ~~~~~~~~~^
Could not build the precompiled application for the device.
```

**Comment by DCrow** [comment]
1. `4.2` value doesn't work in `config.build_settings['SWIFT_VERSION'] = '4.2'`  
It should work with `4.0`
2. It seems that you are using an old version( `5c194d63405d90fed52267ed8cfe9b2b9d2c6f79`)
Could you try it with the current version(`fd7b300e004dddcf028dc90e060a8d593d2d7a91`)?

**Comment by Goolpe** [comment]
I changed version in example project and it works fine. But if I create new project, try add in podfile  `config.build_settings['SWIFT_VERSION'] = '4.0'` , change deployment target to 9.0 - I get this error again.
```
Error output from Xcode build:
↳
    2019-02-27 11:19:04.600 xcodebuild[90936:3832692]  DTDeviceKit: deviceType from 8281cc08213a56923023315c42893a5f4671ab6c was NULL
    ** BUILD FAILED **
Xcode's output:
Undefined symbols for architecture arm64:
  "yandex::maps::runtime::image::Image::data() const", referenced from:
      yandex::maps::mapkit::images::transform(yandex::maps::runtime::image::Image const&, Eigen::Matrix<float, 4, 4, 0, 4, 4> const&) in YandexMapKit(helpers.o)
      yandex::maps::mapkit::decoders::decodeAndLoadRasterTile(yandex::maps::mapkit::TileId const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, yandex::maps::runtime::graphics::Device*, yandex::maps::runtime::async::Dispatcher*, bool, std::__1::function<std::__1::unique_ptr<yandex::maps::runtime::image::Image, std::__1::default_delete<yandex::maps::runtime::image::Image> > (std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&)> const&, std::__1::function<Eigen::Matrix<double, 2, 1, 0, 2, 1> (Eigen::Matrix<double, 2, 1, 0, 2, 1> const&)> const&) in YandexMapKit(raster_tile_decoder.o)
      std::__1::__function::__func<yandex::maps::mapkit::textures::TextureBuilder::createSmallFutureGLTexture()::$_6, std::__1::allocator<yandex::maps::mapkit::textures::TextureBuilder::createSmallFutureGLTexture()::$_6>, void ()>::operator()() in YandexMapKit(texture_builder.o)
      std::__1::__function::__func<yandex::maps::mapkit::textures::TextureBuilder::createLargeFutureGLTexture()::$_8, std::__1::allocator<yandex::maps::mapkit::textures::TextureBuilder::createLargeFutureGLTexture()::$_8>, void ()>::operator()() in YandexMapKit(texture_builder.o)
      yandex::maps::mapkit::textures::Atlas::add(yandex::maps::runtime::image::Image const&) in YandexMapKit(atlas.o)
      std::__1::__function::__func<yandex::maps::mapkit::images::PolylineImageAtlas::add(std::__1::shared_ptr<yandex::maps::runtime::image::Image> const&)::$_0, std::__1::allocator<yandex::maps::mapkit::images::PolylineImageAtlas::add(std::__1::shared_ptr<yandex::maps::runtime::image::Image> const&)::$_0>, void ()>::operator()() in YandexMapKit(polyline_image_atlas.o)
      std::__1::__function::__func<yandex::maps::mapkit::images::PolylineImageAtlas::add(std::__1::vector<std::__1::shared_ptr<yandex::maps::runtime::image::ImageProvider>, std::__1::allocator<std::__1::shared_ptr<yandex::maps::runtime::image::ImageProvider> > > const&)::$_2, std::__1::allocator<yandex::maps::mapkit::images::PolylineImageAtlas::add(std::__1::vector<std::__1::shared_ptr<yandex::maps::runtime::image::ImageProvider>, std::__1::allocator<std::__1::shared_ptr<yandex::maps::runtime::image::ImageProvider> > > const&)::$_2>, void ()>::operator()() in YandexMapKit(polyline_image_atlas.o)
      ...
  "yandex::maps::runtime::graphics::Program::Program(std::__1::function<void (std::__1::function<void ()>)> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::vector<yandex::maps::runtime::graphics::Attribute, std::__1::allocator<yandex::maps::runtime::graphics::Attribute> > const&)", referenced from:
      yandex::maps::mapkit::map::programs::GridProgram::GridProgram(std::__1::function<void (std::__1::function<void ()>)> const&, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::vector<yandex::maps::runtime::graphics::Attribute, std::__1::allocator<yandex::maps::runtime::graphics::Attribute> > const&) in YandexMapKit(grid_program.o)
      yandex::maps::mapkit::textures::StaticImageProgram::StaticImageProgram(std::__1::function<void (std::__1::function<void ()>)> const&, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::vector<yandex::maps::runtime::graphics::Attribute, std::__1::allocator<yandex::maps::runtime::graphics::Attribute> > const&) in YandexMapKit(static_image_program.o)
      yandex::maps::mapkit::render::programs::LabelProgram::LabelProgram(std::__1::function<void (std::__1::function<void ()>)> const&, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::vector<yandex::maps::runtime::graphics::Attribute, std::__1::allocator<yandex::maps::runtime::graphics::Attribute> > const&) in YandexMapKit(label_program.o)
      yandex::maps::mapkit::render::programs::CircleProgram::CircleProgram(std::__1::function<void (std::__1::function<void ()>)> const&, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::vector<yandex::maps::runtime::graphics::Attribute, std::__1::allocator<yandex::maps::runtime::graphics::Attribute> > const&) in YandexMapKit(circle_program.o)
      yandex::maps::mapkit::render::programs::BasePolygonProgram::BasePolygonProgram(std::__1::function<void (std::__1::function<void ()>)> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::vector<yandex::maps::runtime::graphics::Attribute, std::__1::allocator<yandex::maps::runtime::graphics::Attribute> > const&) in YandexMapKit(polygon_program.o)
      yandex::maps::mapkit::render::programs::BasePolylineProgram::BasePolylineProgram(std::__1::function<void (std::__1::function<void ()>)> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::vector<yandex::maps::runtime::graphics::Attribute, std::__1::allocator<yandex::maps::runtime::graphics::Attribute> > const&) in YandexMapKit(polyline_program.o)
      yandex::maps::mapkit::render::programs::BaseFlatPlacemarkProgram::BaseFlatPlacemarkProgram(std::__1::function<void (std::__1::function<void ()>)> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::unique_ptr<yandex::maps::runtime::graphics::Shader, std::__1::default_delete<yandex::maps::runtime::graphics::Shader> >, std::__1::vector<yandex::maps::runtime::graphics::Attribute, std::__1::allocator<yandex::maps::runtime::graphics::Attribute> > const&) in YandexMapKit(flat_placemark_program.o)
      ...
     (maybe you meant: __ZN6yandex4maps7runtime8graphics7ProgramC2ERKNSt3__18functionIFvNS5_IFvvEEEEEERKNS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEENS4_10unique_ptrINS2_6ShaderENS4_14default_deleteISL_EEEESO_RKNS4_6vectorINS2_9AttributeENSF_ISQ_EEEERKNSP_INS2_12UniformBlockENSF_ISV_EEEE)
  "yandex::maps::runtime::memory_pool::memoryPool()", referenced from:
      boost::detail::variant::destroyer::result_type boost::detail::variant::visitation_impl<mpl_::int_<0>, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<2l>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, boost::mpl::l_item<mpl_::long_<1l>, std::__1::unique_ptr<unsigned char, yandex::maps::runtime::memory_pool::Deleter>, boost::mpl::l_end> > >, boost::mpl::l_iter<boost::mpl::l_end> >, boost::detail::variant::destroyer, void*, boost::variant<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::unique_ptr<unsigned char, yandex::maps::runtime::memory_pool::Deleter> >::has_fallback_type_>(int, int, boost::detail::variant::destroyer&, void*, mpl_::bool_<false>, boost::variant<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::unique_ptr<unsigned char, yandex::maps::runtime::memory_pool::Deleter> >::has_fallback_type_, mpl_::int_<0>*, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<2l>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, boost::mpl::l_item<mpl_::long_<1l>, std::__1::unique_ptr<unsigned char, yandex::maps::runtime::memory_pool::Deleter>, boost::mpl::l_end> > >, boost::mpl::l_iter<boost::mpl::l_end> >*) in YandexMapKit(image_loader_impl.o)
  "yandex::maps::runtime::memory_pool::MemoryPool::deallocate(void*, unsigned long)", referenced from:
      boost::detail::variant::destroyer::result_type boost::detail::variant::visitation_impl<mpl_::int_<0>, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<2l>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, boost::mpl::l_item<mpl_::long_<1l>, std::__1::unique_ptr<unsigned char, yandex::maps::runtime::memory_pool::Deleter>, boost::mpl::l_end> > >, boost::mpl::l_iter<boost::mpl::l_end> >, boost::detail::variant::destroyer, void*, boost::variant<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::unique_ptr<unsigned char, yandex::maps::runtime::memory_pool::Deleter> >::has_fallback_type_>(int, int, boost::detail::variant::destroyer&, void*, mpl_::bool_<false>, boost::variant<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, std::__1::unique_ptr<unsigned char, yandex::maps::runtime::memory_pool::Deleter> >::has_fallback_type_, mpl_::int_<0>*, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<2l>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, boost::mpl::l_item<mpl_::long_<1l>, std::__1::unique_ptr<unsigned char, yandex::maps::runtime::memory_pool::Deleter>, boost::mpl::l_end> > >, boost::mpl::l_iter<boost::mpl::l_end> >*) in YandexMapKit(image_loader_impl.o)
  "yandex::maps::runtime::async::internal::logUnknownException(yandex::maps::runtime::backtrace::Backtrace const&)", referenced from:
      yandex::maps::runtime::async::internal::PackagedTaskCommon<yandex::maps::runtime::async::Promise<void, yandex::maps::runtime::async::Handle>, (yandex::maps::runtime::async::Policy)1>::operator()() in YandexMapKit(YMKNativeSession.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

 And if I replace iOS folder from example to my project it works fine too. Maybe you changed something in example Xcode or my Xcode is broken(but other packages work well on ios...)

**Comment by Goolpe** [comment]
And sorry for so many questions, but do you have this issue now https://github.com/flutter/flutter/issues/24207 or solved it?

**Comment by DCrow** [comment]
How are you adding in the plugin in your `pubspec.yaml`?
Are you setting the version correctly?
Could you share your `pubspec.lock` file? 

As for flutter/flutter#24207 - All touch events are working, but I still sometimes receive errors. 
Those errors were moved to flutter/flutter#27700

**Comment by Goolpe** [comment]
I tried so (master branch)
```
dev_dependencies:
  yandex_mapkit:
    path: ./yandex_mapkit
```
and so
```
yandex_mapkit:
    git:
      url: git://github.com/Unact/yandex_mapkit
      ref: fd7b300e004dddcf028dc90e060a8d593d2d7a91
```
if I take ios folder from example and pass in my project - work fine with this dependencies( I'm not changing dependencies - only folder)

**Comment by AndreyTCR** [comment]
I am having same error: not found for architecture arm64. Maybe we must change some settings in xcode project?

**Comment by Goolpe** [comment]
I found. Podfile.lock -> - YandexRuntime must to be (3.2.0) . If I create new project - YandexRuntime is (3.3.1)

**Comment by DCrow** [comment]
I've locked `YandexRuntime` version to 3.2. 
Changed in this [branch](https://github.com/Unact/yandex_mapkit/tree/fix_dependency)
Could you see if it helps?

**Comment by Goolpe** [comment]
It's working, thank you. Will you add your package to pub.dartlang.org?

**Comment by DCrow** [comment]
Yes. It should be available shortly at https://pub.dartlang.org/packages/yandex_mapkit

**Comment by DCrow** [comment]
Closing since the problem was fixed

**Comment by KshetriDeepen** [comment]
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `flutter_text_to_speech` from `.symlinks/plugins/flutter_text_to_speech/ios`
    -> Fetching podspec for `flutter_tts` from `.symlinks/plugins/flutter_tts/ios`
    -> Fetching podspec for `razorpay` from `.symlinks/plugins/razorpay/ios`
    -> Fetching podspec for `tflite` from `.symlinks/plugins/tflite/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Firebase
      A FirebaseAnalytics
      A FirebaseCore
      A FirebaseInstanceID
      A Flutter
      A GoogleAppMeasurement
      A GoogleUtilities
      A TensorFlowLite
      A camera
      A firebase_core
      A flutter_text_to_speech
      A flutter_tts
      A nanopb
      A razorpay
      A tflite

    Downloading dependencies

    -> Installing Firebase (6.3.0)
      > Copying Firebase from `/Users/macbookrosegold/Library/Caches/CocoaPods/Pods/Release/Firebase/6.3.0-8432d` to `Pods/Firebase`

    -> Installing FirebaseAnalytics (6.0.2)
      > Copying FirebaseAnalytics from `/Users/macbookrosegold/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalytics/6.0.2-470dd` to `Pods/FirebaseAnalytics`

    -> Installing FirebaseCore (6.0.3)
      > Copying FirebaseCore from `/Users/macbookrosegold/Library/Caches/CocoaPods/Pods/Release/FirebaseCore/6.0.3-68f8a` to `Pods/FirebaseCore`

    -> Installing FirebaseInstanceID (4.2.0)
      > Copying FirebaseInstanceID from `/Users/macbookrosegold/Library/Caches/CocoaPods/Pods/Release/FirebaseInstanceID/4.2.0-f2024` to `Pods/FirebaseInstanceID`

    -> Installing Flutter (1.0.0)

    -> Installing GoogleAppMeasurement (6.0.2)
      > Copying GoogleAppMeasurement from `/Users/macbookrosegold/Library/Caches/CocoaPods/Pods/Release/GoogleAppMeasurement/6.0.2-a35a6` to `Pods/GoogleAppMeasurement`

    -> Installing GoogleUtilities (6.2.0)
      > Copying GoogleUtilities from `/Users/macbookrosegold/Library/Caches/CocoaPods/Pods/Release/GoogleUtilities/6.2.0-996e0` to `Pods/GoogleUtilities`

    -> Installing TensorFlowLite (1.13.1)
      > Copying TensorFlowLite from `/Users/macbookrosegold/Library/Caches/CocoaPods/Pods/Release/TensorFlowLite/1.13.1-8b9dc` to `Pods/TensorFlowLite`

    -> Installing camera (0.0.1)

    -> Installing firebase_core (0.0.1)
     > Running prepare command
       $ /bin/bash -c  set -e echo // Generated file, do not edit > Classes/UserAgent.h echo "#define LIBRARY_VERSION @\"0.4.0-6\"" >> Classes/UserAgent.h echo "#define LIBRARY_NAME @\"flutter-fire-core\"" >> Classes/UserAgent.h

    -> Installing flutter_text_to_speech (2.0.0)

    -> Installing flutter_tts (0.0.1)

    -> Installing nanopb (0.3.901)
      > Copying nanopb from `/Users/macbookrosegold/Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f` to `Pods/nanopb`

    -> Installing razorpay (0.0.1)

    -> Installing tflite (1.0.4)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `flutter_tts` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `razorpay` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:578:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:158:in `install!'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone Xʀ.
